services:
  ################################
  ################################
  ############ Gluetun ###########
  ################################
  ################################
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun-stack
    # Hostname to use for container, required in some instances for the rest of the stack to each other endpoints 
    hostname: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun 
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: always
    ports:
      - 10025:6881
      - 10026:8085 # qbittorrent
      - 10027:9117 # Jackett
      - 10028:8989 # Sonarr TV
      - 10029:9696 # Prowlarr
      - 10030:8096 # Jellyseer
      - 10031:6767 # Bazarr
      - 10032:8000 # Gluetun web
      - 10033:7878 # Radarr
      - 10034:8191 # FlareSolverr
      - 10035:8990 # Sonarr Anime
    volumes:
      - /opt/stacks/arr-stack/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      - WIREGUARD_ADDRESSES=10.148.164.186/32
      - SERVER_COUNTRIES=${VPN_COUNTRY}
      - FIREWALL_VPN_INPUT_PORTS=49427
      - TZ=${TIMEZONE}
      - UPDATER_PERIOD=24h
      - HTTP_CONTROL_SERVER_AUTH_CONFIG_FILEPATH=./config.toml
      # HEALTHCHECK CONFIGURATION
      - HEALTH_TARGET_ADDRESS=cloudflare.com:443
      - HEALTH_VPN_DURATION_INITIAL=6s
      - HEALTH_VPN_DURATION_ADDITION=5s
      - HEALTH_SUCCESS_WAIT_DURATION=5s
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999

  ################################
  ################################
  ######### qbittorrent ##########
  ################################
  ################################
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent-stack
    network_mode: service:gluetun
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8085
    volumes:
      - /opt/stacks/arr-stack/qbittorrent:/config
      - /mnt/synology/Download:/downloads
      - /opt/extFiles/VueTorrent:/config/VueTorrent
    depends_on:
      - gluetun
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085"]
      interval: 1m
      timeout: 10s
      retries: 3

    ################################
    ################################
    ############ jackett ###########
    ################################
    ################################
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett-stack
    network_mode: service:gluetun
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TIMEZONE}
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /opt/stacks/arr-stack/jackett/data:/config
      - /opt/stacks/arr-stack/jackett/blackhole:/downloads
    depends_on:
      - gluetun
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9117/"]
      interval: 1m
      timeout: 10s
      retries: 3

    ################################
    ################################
    ############ SONARR TV #########
    ################################
    ################################

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-stack
    network_mode: service:gluetun
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TIMEZONE}
    volumes:
      - /opt/stacks/arr-stack/sonarr/data:/config
      - /mnt/synology/Download:/downloads
      - /mnt/synology/SerieTV:/multimedia/serie
    depends_on:
      - gluetun
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989"]
      interval: 1m
      timeout: 10s
      retries: 3

    ################################
    ################################
    ######### SONARR ANIME #########
    ################################
    ################################

  sonarr-anime:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-anime
    network_mode: service:gluetun
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TIMEZONE}
      - PORT=8990
    volumes:
      - /opt/stacks/arr-stack/sonarr-anime/data:/config
      - /mnt/synology/Download:/downloads
      - /mnt/synology/Anime:/multimedia/anime
    depends_on:
      - gluetun
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9696"]
      interval: 1m
      timeout: 10s
      retries: 3

    ################################
    ################################
    ############ prowlarr ##########
    ################################
    ################################
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr-stack
    network_mode: service:gluetun
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TIMEZONE}
    volumes:
      - /opt/stacks/arr-stack/prowlarr/data:/config
    depends_on:
      - gluetun
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9696"]
      interval: 1m
      timeout: 10s
      retries: 3
    ################################
    ################################
    ########## jellyseerr ##########
    ################################
    ################################
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseer-stack
    network_mode: service:gluetun
    environment:
      - LOG_LEVEL=debug
      - TZ=${TIMEZONE}
      - PORT=8096
    volumes:
      - /opt/stacks/arr-stack/jellyseer/config:/app/config
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096"]
      interval: 1m
      timeout: 10s
      retries: 3


    ################################
    ################################
    ############ Bazarr ############
    ################################
    ################################
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr-stack
    network_mode: service:gluetun
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TIMEZONE}
    volumes:
      - /opt/stacks/arr-stack/bazarr/config:/config
      - /mnt/synology/Anime:/multimedia/anime
      - /mnt/synology/SerieTV:/multimedia/serie
      - /mnt/synology/Film:/multimedia/film
    depends_on:
      - gluetun
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6767"]
      interval: 1m
      timeout: 10s
      retries: 3

    ################################
    ################################
    ############ Radarr ############
    ################################
    ################################
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: service:gluetun
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TIMEZONE}
    volumes:
      - /opt/stacks/arr-stack/radarr/config:/config
      - /mnt/synology/Download:/downloads
      - /mnt/synology/Anime:/multimedia/anime
      - /mnt/synology/SerieTV:/multimedia/serie
      - /mnt/synology/Film:/multimedia/film
    depends_on:
      - gluetun
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7878"]
      interval: 1m
      timeout: 10s
      retries: 3

    ################################
    ################################
    ########## FlareSolverr ########
    ################################
    ################################

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr-stack
    network_mode: service:gluetun
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TIMEZONE}
    depends_on:
      - gluetun
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8191/health"]
      interval: 1m
      timeout: 10s
      retries: 3
networks: {}
