version: "3"
services:
  ################################
  ################################
  ############ Gluetun ###########
  ################################
  ################################
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun-stack
    # Hostname to use for container, required in some instances for the rest of the stack to each other endpoints 
    hostname: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 10025:6881
      - 10026:8085 # qbittorrent
      - 10027:9117 # Jackett
      - 10028:8989 # Sonarr
      - 10029:9696 # Prowlarr
      - 10030:8096 # Jellyseer
      - 10031:6767 # Bazarr
      - 10032:8000 # Gluetun web
    volumes:
      - /opt/stacks/arr-stack/gluetun:/gluetun
    environment:
      # see https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers/nordvpn.md
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn # or wireguard
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=Italy
      - TZ=${TIMEZONE}
      - UPDATER_PERIOD=24h
      - HTTP_CONTROL_SERVER_AUTH_CONFIG_FILEPATH=./config.toml
    ################################
    ################################
    ######### qbittorrent ##########
    ################################
    ################################
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent-stack
    network_mode: service:gluetun
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8085
    volumes:
      - /opt/stacks/arr-stack/qbittorrent:/config
      - /mnt/synology/Download:/downloads
      - /opt/extFiles/VueTorrent:/config/VueTorrent
    depends_on:
      - gluetun
    restart: always
    ################################
    ################################
    ############ jackett ###########
    ################################
    ################################
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett-stack
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - /opt/stacks/arr-stack/jackett/data:/config
      - /opt/stacks/arr-stack/jackett/blackhole:/downloads
    depends_on:
      - gluetun
    restart: always
    ################################
    ################################
    ############ SONARR ############
    ################################
    ################################

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-stack
    network_mode: service:gluetun
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TIMEZONE}
    volumes:
      - /opt/stacks/arr-stack/sonarr/data:/config
      - /mnt/synology/Download:/downloads
      - /mnt/synology/Anime:/multimedia/anime
      - /mnt/synology/SerieTV:/multimedia/serie
      - /mnt/synology/Film:/multimedia/film
    depends_on:
      - gluetun
    restart: always
    ################################
    ################################
    ############ prowlarr ##########
    ################################
    ################################
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr-stack
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - /opt/stacks/arr-stack/prowlarr/data:/config
    depends_on:
      - gluetun
    restart: always
    ################################
    ################################
    ########## jellyseerr ##########
    ################################
    ################################
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseer-stack
    network_mode: service:gluetun
    environment:
      - LOG_LEVEL=debug
      - TZ=${TIMEZONE}
      - PORT=8096
    volumes:
      - /opt/stacks/arr-stack/jellyseer/config:/app/config
    restart: always
    ################################
    ################################
    ############ Bazarr ############
    ################################
    ################################
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr-stack
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - /opt/stacks/arr-stack/bazarr/config:/config
      - /mnt/synology/Anime:/multimedia/anime
      - /mnt/synology/SerieTV:/multimedia/serie
      - /mnt/synology/Film:/multimedia/film
    depends_on:
      - gluetun
    restart: always
networks: {}
